import { z } from "zod";
import type { Endpoint } from "better-call";
import {
	type AnyAuthorization,
	type AnyPermissionDescriptor,
	type PermissionFactsFor,
	type PermissionInputFor,
	type PermissionRequest,
	type PermissionRequestFor,
} from "../../authorization";
import type { ServerAuth } from "../../authorization/server";
import type { StackIdentity } from "../../shared/auth-types";
import type { MaybePromise } from "../../shared/types";

interface OperationExecutionOptions {
	request?: Request;
	auth?: ServerAuth<AnyAuthorization>;
	skipAuthorization: boolean;
}

/** Whether a request operation requires identity authorization. */
export type OperationAccess = "authorized" | "public";

/** How an operation result crosses the lifecycle boundary. */
export type OperationResultMode = "immutable" | "passthrough";

/**
 * A domain failure that is safe for an HTTP operation route to expose.
 * Identity, rule, fact, and ordinary execution errors are intentionally not
 * converted at the transport boundary.
 */
export class OperationHttpError extends Error {
	readonly statusCode: number;
	readonly code: string;
	readonly issues?: readonly unknown[];

	constructor(
		statusCode: number,
		message: string,
		code: string,
		issues?: readonly unknown[],
	) {
		super(message);
		this.name = "OperationHttpError";
		this.statusCode = statusCode;
		this.code = code;
		this.issues = issues;
	}
}

type OperationExecutor = (
	input: unknown,
	options: OperationExecutionOptions,
) => Promise<unknown>;

const operationExecutors = new WeakMap<object, OperationExecutor>();
const operationInputValidationErrors = new WeakSet<object>();
interface RouteOperationBinding {
	readonly pluginKey: string;
	readonly operationKey: string;
	readonly operation: AnyOperation;
}
const routeOperationBindings = new WeakMap<object, RouteOperationBinding>();

/** @internal Mark a handler generated by one exact request operation transport. */
export function bindRouteOperationHandler<THandler extends object>(
	handler: THandler,
	binding: RouteOperationBinding,
): THandler {
	routeOperationBindings.set(handler, binding);
	return handler;
}

/** @internal Carry a generated handler's transport binding onto its endpoint. */
export function bindRouteOperationEndpoint<TEndpoint extends object>(
	endpoint: TEndpoint,
	handler: object,
): TEndpoint {
	const binding = routeOperationBindings.get(handler);
	if (!binding) return endpoint;
	const existing = routeOperationBindings.get(endpoint);
	if (existing !== undefined && existing !== binding) {
		throw new TypeError(
			`Endpoint is already bound to operation "${existing.pluginKey}.${existing.operationKey}" and cannot also bind to "${binding.pluginKey}.${binding.operationKey}".`,
		);
	}
	routeOperationBindings.set(endpoint, binding);
	return endpoint;
}

/** @internal Read the non-serializable operation transport marker. */
export function getRouteEndpointOperationBinding(
	endpoint: Endpoint,
): RouteOperationBinding | undefined {
	return routeOperationBindings.get(endpoint);
}

/** @internal True only for the source-of-truth operation input parse. */
export function isOperationInputValidationError(
	cause: unknown,
): cause is z.ZodError {
	return (
		typeof cause === "object" &&
		cause !== null &&
		operationInputValidationErrors.has(cause)
	);
}

/** Plain values accepted at the immutable operation lifecycle boundary. */
export type OperationData =
	| string
	| number
	| boolean
	| bigint
	| null
	| undefined
	| readonly OperationData[]
	| { readonly [key: string]: OperationData };

/** Recursively readonly data exposed by an authorized operation lifecycle. */
export type DeepReadonly<T> = T extends (...args: any[]) => unknown
	? T
	: T extends readonly unknown[]
		? { readonly [TKey in keyof T]: DeepReadonly<T[TKey]> }
		: T extends object
			? { readonly [TKey in keyof T]: DeepReadonly<T[TKey]> }
			: T;

function freezeOperationData<T>(
	value: T,
	seen = new WeakSet<object>(),
	path = "operation data",
): DeepReadonly<T> {
	if (
		value === null ||
		(typeof value !== "object" && typeof value !== "function")
	) {
		if (typeof value === "function" || typeof value === "symbol") {
			throw new TypeError(`${path} must contain only plain immutable data.`);
		}
		return value as DeepReadonly<T>;
	}

	const object = value as object;
	const prototype = Object.getPrototypeOf(object);
	if (
		!Array.isArray(object) &&
		prototype !== Object.prototype &&
		prototype !== null
	) {
		throw new TypeError(
			`${path} must contain only plain objects and arrays; mutable built-ins are not supported.`,
		);
	}
	if (seen.has(object)) {
		throw new TypeError(`${path} must not contain circular references.`);
	}
	seen.add(object);
	for (const key of Reflect.ownKeys(object)) {
		if (typeof key === "symbol") {
			throw new TypeError(`${path} must not contain symbol properties.`);
		}
		const descriptor = Object.getOwnPropertyDescriptor(object, key);
		if (descriptor && !("value" in descriptor)) {
			throw new TypeError(`${path} must not contain accessor properties.`);
		}
		freezeOperationData(
			(object as Record<PropertyKey, unknown>)[key],
			seen,
			`${path}.${key}`,
		);
	}
	seen.delete(object);
	return Object.freeze(object) as DeepReadonly<T>;
}

/** Validated input, trusted facts, and resolved identity passed through an operation. */
export interface OperationContext<TInput, TFacts> {
	readonly input: DeepReadonly<TInput>;
	readonly facts: DeepReadonly<TFacts>;
	readonly identity: DeepReadonly<StackIdentity> | null;
	readonly request?: Request;
}

/** Context available after an authorized operation enters its lifecycle. */
export interface OperationErrorContext<TInput, TFacts>
	extends OperationContext<TInput, TFacts> {
	readonly error: unknown;
}

/** A validated plugin operation shared by every server transport. */
export interface Operation<
	TInputSchema extends z.ZodTypeAny = z.ZodTypeAny,
	TPermission extends AnyPermissionDescriptor = AnyPermissionDescriptor,
	TResult = unknown,
	TPassthroughResult extends boolean = false,
> {
	readonly input: TInputSchema;
	readonly permission: TPermission;
	readonly access: OperationAccess;
	readonly resultMode: TPassthroughResult extends true
		? "passthrough"
		: "immutable";
}

/** Any plugin operation, for generic stack composition. */
export type AnyOperation =
	| Operation<z.ZodTypeAny, AnyPermissionDescriptor, any, false>
	| Operation<z.ZodTypeAny, AnyPermissionDescriptor, any, true>;
/** Named operations exposed by a backend plugin. */
export type OperationRecord = Record<string, AnyOperation>;

type OperationInput<TOperation extends AnyOperation> =
	TOperation extends Operation<infer TInputSchema, any, any, any>
		? z.input<TInputSchema>
		: never;

type OperationTransportResult<TOperation extends AnyOperation> =
	TOperation extends Operation<
		any,
		any,
		infer TResult,
		infer TPassthroughResult
	>
		? TPassthroughResult extends true
			? TResult
			: DeepReadonly<TResult>
		: never;

/** Infer the permission request enforced by an operation. */
export type OperationPermissionRequest<TOperation extends AnyOperation> =
	TOperation extends Operation<any, infer TPermission, any, any>
		? PermissionRequestFor<TPermission>
		: never;

/** Infer the stable permission id enforced by an operation. */
export type OperationPermissionId<TOperation extends AnyOperation> =
	OperationPermissionRequest<TOperation>["id"];

/** Convert operation definitions into their bound callable application API. */
export type OperationApi<TOperations extends OperationRecord> = {
	[TKey in keyof TOperations]: (
		input: OperationInput<TOperations[TKey]>,
	) => Promise<OperationTransportResult<TOperations[TKey]>>;
};

/** One request-bound operation plus its endpoint-binding helper. */
export type RouteOperation<TOperation extends AnyOperation> = {
	(
		input: OperationInput<TOperation>,
		request: Request,
	): Promise<OperationTransportResult<TOperation>>;
	/** Generate an endpoint handler that always executes this exact operation. */
	route<
		TContext extends {
			readonly request: Request;
			readonly error: (...args: any[]) => Error;
		},
	>(
		resolveInput: (
			context: TContext,
		) => MaybePromise<OperationInput<TOperation>>,
	): (context: TContext) => Promise<OperationTransportResult<TOperation>>;
};

/** Operations bound to an HTTP transport; every call requires its request. */
export type RouteOperationApi<TOperations extends OperationRecord> = {
	[TKey in keyof TOperations]: RouteOperation<TOperations[TKey]>;
};

/** Shared configuration shape for immutable and passthrough operations. */
type OperationConfig<
	TInputSchema extends z.ZodTypeAny,
	TPermission extends AnyPermissionDescriptor,
	TExecute extends (
		ctx: OperationContext<
			z.output<TInputSchema>,
			PermissionFactsFor<TPermission>
		>,
	) => MaybePromise<unknown>,
	TResult,
> = {
	input: [z.output<TInputSchema>] extends [OperationData]
		? TInputSchema
		: never;
	permission: [PermissionFactsFor<TPermission>] extends [OperationData]
		? TPermission
		: never;
	/**
	 * Explicitly bypass request identity authorization for this one operation.
	 * Validation, trusted fact derivation, lifecycle hooks, and execution still run.
	 * @default "authorized"
	 */
	access?: OperationAccess;
	facts: (ctx: {
		readonly input: DeepReadonly<z.output<TInputSchema>>;
		readonly request?: Request;
	}) => MaybePromise<PermissionInputFor<TPermission>>;
	/**
	 * Derive any compound permission checks from validated input and trusted
	 * primary facts after request execution authorizes the primary permission.
	 * Every returned request is authorized before lifecycle hooks run; trusted
	 * internal execution skips only the evaluations.
	 */
	additionalPermissions?: (ctx: {
		readonly input: DeepReadonly<z.output<TInputSchema>>;
		readonly facts: DeepReadonly<PermissionFactsFor<TPermission>>;
		readonly request?: Request;
	}) => MaybePromise<readonly PermissionRequest<string, any>[]>;
	before?: (
		ctx: OperationContext<
			z.output<TInputSchema>,
			PermissionFactsFor<TPermission>
		>,
	) => MaybePromise<void>;
	execute: TExecute;
	after?: (
		ctx: OperationContext<
			z.output<TInputSchema>,
			PermissionFactsFor<TPermission>
		> & {
			readonly result: TResult;
		},
	) => MaybePromise<void>;
	onError?: (
		ctx: OperationErrorContext<
			z.output<TInputSchema>,
			PermissionFactsFor<TPermission>
		>,
	) => MaybePromise<void>;
};

/**
 * Define validation, trusted fact derivation, authorization, lifecycle hooks,
 * and execution once so transports cannot accidentally bypass the pipeline.
 *
 * The operation descriptor deliberately has no public `run()` method. Stack
 * composition binds it to HTTP, `forRequest()`, and the explicit `internal`
 * namespace so callers cannot forge an internal execution flag.
 */
export function defineOperation<
	const TInputSchema extends z.ZodTypeAny,
	const TPermission extends AnyPermissionDescriptor,
	const TExecute extends (
		ctx: OperationContext<
			z.output<TInputSchema>,
			PermissionFactsFor<TPermission>
		>,
	) => MaybePromise<OperationData>,
>(config: {
	input: [z.output<TInputSchema>] extends [OperationData]
		? TInputSchema
		: never;
	permission: [PermissionFactsFor<TPermission>] extends [OperationData]
		? TPermission
		: never;
	/**
	 * Explicitly bypass request identity authorization for this one operation.
	 * Validation, trusted fact derivation, lifecycle hooks, and execution still run.
	 * @default "authorized"
	 */
	access?: OperationAccess;
	facts: (ctx: {
		readonly input: DeepReadonly<z.output<TInputSchema>>;
		readonly request?: Request;
	}) => MaybePromise<PermissionInputFor<TPermission>>;
	additionalPermissions?: (ctx: {
		readonly input: DeepReadonly<z.output<TInputSchema>>;
		readonly facts: DeepReadonly<PermissionFactsFor<TPermission>>;
		readonly request?: Request;
	}) => MaybePromise<readonly PermissionRequest<string, any>[]>;
	before?: (
		ctx: OperationContext<
			z.output<TInputSchema>,
			PermissionFactsFor<TPermission>
		>,
	) => MaybePromise<void>;
	execute: TExecute;
	after?: (
		ctx: OperationContext<
			z.output<TInputSchema>,
			PermissionFactsFor<TPermission>
		> & {
			readonly result: DeepReadonly<Awaited<ReturnType<TExecute>>>;
		},
	) => MaybePromise<void>;
	onError?: (
		ctx: OperationErrorContext<
			z.output<TInputSchema>,
			PermissionFactsFor<TPermission>
		>,
	) => MaybePromise<void>;
}): Operation<TInputSchema, TPermission, Awaited<ReturnType<TExecute>>>;
export function defineOperation(config: any): AnyOperation {
	return defineOperationRuntime(config, false);
}

/**
 * Define an operation whose transport-native result must retain its runtime
 * identity (for example a streaming `Response`). Input, facts, identity,
 * authorization, and lifecycle ordering remain identical to `defineOperation`;
 * only the result skips recursive freezing.
 */
export function definePassthroughOperation<
	const TInputSchema extends z.ZodTypeAny,
	const TPermission extends AnyPermissionDescriptor,
	const TExecute extends (
		ctx: OperationContext<
			z.output<TInputSchema>,
			PermissionFactsFor<TPermission>
		>,
	) => MaybePromise<unknown>,
>(
	config: OperationConfig<
		TInputSchema,
		TPermission,
		TExecute,
		Awaited<ReturnType<TExecute>>
	>,
): Operation<TInputSchema, TPermission, Awaited<ReturnType<TExecute>>, true>;
export function definePassthroughOperation(config: any): AnyOperation {
	return defineOperationRuntime(config, true);
}

function defineOperationRuntime<
	TInputSchema extends z.ZodTypeAny = z.ZodTypeAny,
	TPermission extends AnyPermissionDescriptor = AnyPermissionDescriptor,
>(config: any, passthroughResult: boolean): AnyOperation {
	const operationAccess = config.access ?? "authorized";
	if (operationAccess !== "authorized" && operationAccess !== "public") {
		throw new TypeError(
			'Operation access must be either "authorized" or "public".',
		);
	}
	const runtimePermission = config.permission as unknown as {
		(): { facts: unknown };
		(facts: unknown): { facts: unknown };
	};

	const executeOperation = async (
		input: z.input<TInputSchema>,
		options: OperationExecutionOptions,
	): Promise<unknown> => {
		// These stages establish trusted operation context. They intentionally run
		// before the lifecycle boundary, so validation, fact, identity, and rule
		// failures cannot be observed or replaced by post-authorization hooks.
		let validatedInput: z.output<TInputSchema>;
		try {
			validatedInput = config.input.parse(input);
		} catch (cause) {
			if (cause instanceof z.ZodError) {
				operationInputValidationErrors.add(cause);
			}
			throw cause;
		}
		const parsedInput = freezeOperationData(
			validatedInput,
			new WeakSet(),
			"operation input",
		);
		const trustedFacts = await config.facts({
			input: parsedInput,
			...(options.request ? { request: options.request } : {}),
		});
		const permissionRequest = config.permission.schema
			? runtimePermission(trustedFacts)
			: runtimePermission();
		const parsedFacts = freezeOperationData(
			permissionRequest.facts as PermissionFactsFor<TPermission>,
			new WeakSet(),
			"operation facts",
		);
		let identity: DeepReadonly<StackIdentity> | null = null;
		let runtimeAuth:
			| {
					authorize: (
						request: Request,
						permission: unknown,
					) => Promise<StackIdentity | null>;
			  }
			| undefined;
		if (
			!options.skipAuthorization &&
			operationAccess === "authorized" &&
			options.auth
		) {
			if (!options.request) {
				throw new Error("Authorized operations require a request.");
			}
			runtimeAuth = options.auth as unknown as NonNullable<typeof runtimeAuth>;
			const authorizedIdentity = await runtimeAuth.authorize(
				options.request,
				permissionRequest,
			);
			identity = authorizedIdentity
				? freezeOperationData(
						authorizedIdentity,
						new WeakSet(),
						"operation identity",
					)
				: null;
		}

		// Compound checks may perform trusted reads. Derive them only after the
		// primary request is authorized so denied callers cannot trigger that work
		// or replace the primary 401/403 with a derivation error. Internal execution
		// still derives the requests because execute() may validate their snapshots.
		const additionalPermissions =
			(await config.additionalPermissions?.({
				input: parsedInput,
				facts: parsedFacts,
				...(options.request ? { request: options.request } : {}),
			})) ?? [];
		if (!Array.isArray(additionalPermissions)) {
			throw new TypeError(
				"Operation additionalPermissions() must return an array of permission requests.",
			);
		}
		if (runtimeAuth && options.request) {
			for (const additionalPermission of additionalPermissions) {
				await runtimeAuth.authorize(options.request, additionalPermission);
			}
		}

		const context = Object.freeze({
			input: parsedInput,
			facts: parsedFacts,
			identity,
			...(options.request ? { request: options.request } : {}),
		}) satisfies OperationContext<
			z.output<TInputSchema>,
			PermissionFactsFor<TPermission>
		>;

		try {
			await config.before?.(context);
			const executed = await config.execute(context);
			const result = passthroughResult
				? executed
				: freezeOperationData<unknown>(
						executed,
						new WeakSet(),
						"operation result",
					);
			const after = config.after as
				| ((ctx: unknown) => MaybePromise<void>)
				| undefined;
			await after?.(Object.freeze({ ...context, result }));
			return result;
		} catch (error) {
			try {
				await config.onError?.(Object.freeze({ ...context, error }));
			} catch {
				// Error hooks are observational and must not replace the operation error.
			}
			throw error;
		}
	};

	const operation = {
		input: config.input,
		permission: config.permission,
		access: operationAccess,
		resultMode: passthroughResult ? "passthrough" : "immutable",
	} as AnyOperation;
	operationExecutors.set(operation, executeOperation as OperationExecutor);
	return Object.freeze(operation);
}

function getOperationExecutor(operation: AnyOperation): OperationExecutor {
	const executor = operationExecutors.get(operation);
	if (!executor) throw new TypeError("Invalid operation descriptor.");
	return executor;
}

/** @internal Execute an operation through an authorized request transport. */
export function runAuthorizedOperation<TOperation extends AnyOperation>(
	operation: TOperation,
	input: OperationInput<TOperation>,
	options: {
		request: Request;
		auth?: ServerAuth<AnyAuthorization>;
	},
): Promise<OperationTransportResult<TOperation>> {
	return getOperationExecutor(operation)(input, {
		request: options.request,
		...(options.auth ? { auth: options.auth } : {}),
		skipAuthorization: false,
	}) as Promise<OperationTransportResult<TOperation>>;
}

/** @internal Execute an operation through the trusted application namespace. */
export function runInternalOperation<TOperation extends AnyOperation>(
	operation: TOperation,
	input: OperationInput<TOperation>,
): Promise<OperationTransportResult<TOperation>> {
	return getOperationExecutor(operation)(input, {
		skipAuthorization: true,
	}) as Promise<OperationTransportResult<TOperation>>;
}
