"use client";

import { useEffect, useRef, useCallback } from "react";
import type { EmbedOptions, Project } from "@stackblitz/sdk";
import type { FileWritePlanItem } from "@btst/codegen/lib";
import { buildProjectFiles, toSdkFiles } from "@/lib/stackblitz-template";
import { Button } from "@/components/ui/button";

interface StackBlitzEmbedProps {
	generatedFiles: FileWritePlanItem[];
	cssImports: string[];
	extraPackages: string[];
	previewPath?: string | null;
	extraButtons?: React.ReactNode;
}

const EMBED_HEIGHT = 700;

export function StackBlitzEmbed({
	generatedFiles,
	cssImports,
	extraPackages,
	previewPath,
	extraButtons,
}: StackBlitzEmbedProps) {
	const containerRef = useRef<HTMLDivElement>(null);
	const projectRef = useRef<Project | null>(null);
	const vmRef = useRef<import("@stackblitz/sdk").VM | null>(null);
	const previewPathRef = useRef<string | null | undefined>(previewPath);

	useEffect(() => {
		previewPathRef.current = previewPath;
	}, [previewPath]);

	useEffect(() => {
		const container = containerRef.current;
		if (!container) return;

		let cancelled = false;

		const project: Project = {
			title: "BTST Playground Demo",
			description: "Generated by BTST Playground",
			template: "node",
			files: toSdkFiles(
				buildProjectFiles(generatedFiles, cssImports, extraPackages),
			),
		};

		projectRef.current = project;

		const embedOptions: EmbedOptions = {
			height: EMBED_HEIGHT,
			openFile: "app/page.tsx",
			terminalHeight: 30,
			theme: "dark",
			showSidebar: false,
			view: "default",
		};

		const log = (...args: unknown[]) =>
			console.log(`[StackBlitz ${new Date().toISOString()}]`, ...args);

		log("Starting embed — loading SDK...");

		void import("@stackblitz/sdk")
			.then((mod) => {
				if (cancelled || !containerRef.current) return;

				container.innerHTML = "";

				// Create a fresh target for the SDK to replace with its iframe.
				// Never pass containerRef.current itself — the SDK replaces the target
				// element in the DOM, which would break React's reconciliation.
				const target = document.createElement("div");
				container.appendChild(target);

				log("SDK loaded — calling embedProject", {
					template: project.template,
					fileCount: Object.keys(project.files ?? {}).length,
					embedOptions,
				});

				mod.default
					.embedProject(target, project, embedOptions)
					.then((vm) => {
						if (cancelled) return;
						vmRef.current = vm;
						log(
							"VM connected ✓ — WebContainers booting, starting diagnostics...",
						);
						if (previewPathRef.current) {
							vm.preview
								.setUrl(previewPathRef.current)
								.then(() =>
									log(
										"Applied initial preview path request:",
										previewPathRef.current,
									),
								)
								.catch((e) => log("Initial preview path set failed:", e));
						}

						// Snapshot deps to confirm package.json was parsed correctly.
						vm.getDependencies()
							.then((deps) => log("Resolved dependencies:", deps))
							.catch((e) => log("getDependencies failed:", e));

						// Poll preview URL until the dev server is up (or we give up).
						// NOTE: SDK_GET_PREVIEW_URL_FAILURE is thrown when COEP prevents the
						// SDK from reading the cross-origin preview iframe URL. This does NOT
						// mean the VM died — continue polling through it.
						let attempts = 0;
						const maxAttempts = 60; // 5 min — Next.js install takes a while
						const pollInterval = setInterval(async () => {
							if (cancelled) {
								clearInterval(pollInterval);
								return;
							}
							attempts++;
							try {
								const url = await vm.preview.getUrl();
								log(
									`Preview poll #${attempts}: url=${url ?? "null (server not ready yet)"}`,
								);
								if (url) {
									clearInterval(pollInterval);
									log("Dev server is up ✓", { url });
								} else if (attempts >= maxAttempts) {
									clearInterval(pollInterval);
									log(
										`Dev server never came up after ${maxAttempts} polls — likely crashed.`,
									);
									vm.getFsSnapshot()
										.then((files) => {
											const paths = Object.keys(files ?? {});
											log("FS snapshot on crash:", {
												totalFiles: paths.length,
												hasNodeModules: paths.some((p) =>
													p.startsWith("node_modules/"),
												),
												hasNextDir: paths.some((p) => p.startsWith(".next/")),
												samplePaths: paths.slice(0, 20),
											});
										})
										.catch((e) => log("getFsSnapshot failed:", e));
								}
							} catch (e: unknown) {
								const msg = e instanceof Error ? e.message : String(e);
								if (msg.includes("SDK_GET_PREVIEW_URL_FAILURE")) {
									// COEP restricts reading cross-origin preview URL — VM is alive.
									log(
										`Preview poll #${attempts}: COEP blocks preview URL read (VM still alive)`,
									);
								} else {
									clearInterval(pollInterval);
									log(
										"Preview poll threw unexpected error — VM may have died:",
										e,
									);
								}
							}
						}, 5_000);
					})
					.catch((err: unknown) => {
						if (cancelled) return;
						// VM timeout during boot is common — the iframe still renders.
						// Log it anyway so we can distinguish timeout from a real error.
						log("embedProject rejected (VM timeout or boot failure):", err);
					});
			})
			.catch((err: unknown) => {
				if (cancelled) return;
				log("Failed to load StackBlitz SDK:", err);
			});

		return () => {
			cancelled = true;
			vmRef.current = null;
			container.innerHTML = "";
			log("Embed unmounted / deps changed — cleaned up.");
		};
	}, [generatedFiles, cssImports, extraPackages]);

	useEffect(() => {
		if (!previewPath || !vmRef.current) return;
		const vm = vmRef.current;
		vm.preview
			.setUrl(previewPath)
			.catch((e) =>
				console.log(
					`[StackBlitz ${new Date().toISOString()}] Failed to set preview URL`,
					{ previewPath, error: e },
				),
			);
	}, [previewPath]);

	const handleOpenInStackBlitz = useCallback(() => {
		if (!projectRef.current) return;
		void import("@stackblitz/sdk")
			.then((mod) => {
				mod.default.openProject(projectRef.current!, {
					openFile: "app/page.tsx",
				});
			})
			.catch((err: unknown) => {
				console.error(
					`[StackBlitz ${new Date().toISOString()}] Failed to load SDK`,
					err,
				);
			});
	}, []);

	return (
		<div className="w-full flex flex-col gap-2">
			<div className="flex justify-end gap-2">
				{extraButtons}
				<Button variant="outline" onClick={handleOpenInStackBlitz}>
					<svg
						data-icon="inline-start"
						viewBox="0 0 28 28"
						fill="currentColor"
						aria-hidden="true"
					>
						<path d="M12.747 16.273h-7.46L18.925 1.5l-3.671 10.227h7.46L9.075 26.5z" />
					</svg>
					Open in StackBlitz
				</Button>
			</div>
			<div
				ref={containerRef}
				className="w-full rounded-xl overflow-hidden border border-zinc-200 dark:border-zinc-700"
				style={{ height: EMBED_HEIGHT }}
			/>
		</div>
	);
}
