"use client";

import { useEffect, useRef, useState } from "react";
import type { FileWritePlanItem } from "@btst/codegen/lib";
import { buildProjectFiles, toSdkFiles } from "@/lib/stackblitz-template";

interface StackBlitzEmbedProps {
	generatedFiles: FileWritePlanItem[];
	cssImports: string[];
}

export function StackBlitzEmbed({
	generatedFiles,
	cssImports,
}: StackBlitzEmbedProps) {
	const containerRef = useRef<HTMLDivElement>(null);
	const [loading, setLoading] = useState(true);
	const [error, setError] = useState<string | null>(null);
	const vmRef = useRef<any>(null);

	useEffect(() => {
		if (!containerRef.current) return;

		let cancelled = false;

		async function embed() {
			setLoading(true);
			setError(null);

			try {
				// Dynamically import StackBlitz SDK (client-only)
				const sdk = await import("@stackblitz/sdk");

				if (cancelled || !containerRef.current) return;

				const projectFiles = buildProjectFiles(generatedFiles, cssImports);
				const sdkFiles = toSdkFiles(projectFiles);

				// Destroy previous VM if any
				if (vmRef.current) {
					try {
						vmRef.current = null;
					} catch {}
				}

				// Clear container
				containerRef.current.innerHTML = "";

				const vm = await sdk.default.embedProject(
					containerRef.current,
					{
						title: "BTST Playground Demo",
						description: "Generated by BTST Playground",
						template: "node",
						files: sdkFiles,
					},
					{
						height: "100%",
						hideNavigation: false,
						openFile: "app/page.tsx",
						terminalHeight: 30,
						startScript: "dev",
						theme: "dark",
					},
				);

				if (!cancelled) {
					vmRef.current = vm;
					setLoading(false);
				}
			} catch (err) {
				if (!cancelled) {
					setError(
						err instanceof Error
							? err.message
							: "Failed to load StackBlitz embed",
					);
					setLoading(false);
				}
			}
		}

		embed();

		return () => {
			cancelled = true;
		};
	}, [generatedFiles, cssImports]);

	return (
		<div className="relative w-full h-full min-h-[600px] rounded-xl overflow-hidden border border-zinc-200 dark:border-zinc-700">
			{loading && (
				<div className="absolute inset-0 flex flex-col items-center justify-center bg-zinc-950 text-zinc-400 z-10">
					<svg
						className="animate-spin h-8 w-8 mb-3 text-blue-400"
						viewBox="0 0 24 24"
						fill="none"
					>
						<circle
							className="opacity-25"
							cx="12"
							cy="12"
							r="10"
							stroke="currentColor"
							strokeWidth="4"
						/>
						<path
							className="opacity-75"
							fill="currentColor"
							d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"
						/>
					</svg>
					<p className="text-sm">Starting WebContainer…</p>
					<p className="text-xs text-zinc-600 mt-1">
						This may take 30–60 seconds on first load
					</p>
				</div>
			)}
			{error && (
				<div className="absolute inset-0 flex flex-col items-center justify-center bg-zinc-950 text-zinc-400 z-10 p-6 text-center">
					<p className="text-red-400 font-medium mb-2">
						Failed to load StackBlitz
					</p>
					<p className="text-sm text-zinc-500">{error}</p>
					<p className="text-xs text-zinc-600 mt-3">
						Make sure you have cross-origin isolation headers enabled, or try
						opening in Chrome.
					</p>
				</div>
			)}
			<div
				ref={containerRef}
				className="w-full h-full"
				style={{ minHeight: 600 }}
			/>
		</div>
	);
}
