import type { FileWritePlanItem } from "@btst/codegen/lib";

export interface ProjectFile {
	content: string;
}

export type ProjectFiles = Record<string, ProjectFile>;

/**
 * Build the complete StackBlitz project file tree.
 *
 * The base skeleton is a minimal Next.js app wired with the memory adapter.
 * The generated files from buildScaffoldPlan are merged on top (overwriting
 * any skeleton file with the same path).
 */
export function buildProjectFiles(
	generatedFiles: FileWritePlanItem[],
	cssImports: string[],
): ProjectFiles {
	const cssImportLines = cssImports.map((c) => `@import "${c}";`).join("\n");

	const files: ProjectFiles = {
		// ── package.json ────────────────────────────────────────────────────────
		"package.json": {
			content: JSON.stringify(
				{
					name: "btst-playground-demo",
					version: "0.0.0",
					private: true,
					scripts: {
						dev: "next dev",
						build: "next build",
						start: "next start",
					},
					dependencies: {
						"@btst/stack": "latest",
						"@btst/adapter-memory": "latest",
						"@tanstack/react-query": "^5.0.0",
						next: "15.3.4",
						react: "^19.0.0",
						"react-dom": "^19.0.0",
					},
					devDependencies: {
						"@tailwindcss/postcss": "^4.1.10",
						"@types/node": "^24.0.0",
						"@types/react": "^19.0.0",
						"@types/react-dom": "^19.0.0",
						postcss: "^8.5.0",
						tailwindcss: "^4.1.10",
						typescript: "^5.8.0",
					},
				},
				null,
				2,
			),
		},

		// ── next.config.ts ───────────────────────────────────────────────────────
		"next.config.ts": {
			content: `import type { NextConfig } from "next"

const config: NextConfig = {
  reactStrictMode: true,
}

export default config
`,
		},

		// ── tsconfig.json ────────────────────────────────────────────────────────
		"tsconfig.json": {
			content: JSON.stringify(
				{
					compilerOptions: {
						baseUrl: ".",
						target: "ESNext",
						lib: ["dom", "dom.iterable", "esnext"],
						allowJs: true,
						skipLibCheck: true,
						strict: true,
						forceConsistentCasingInFileNames: true,
						noEmit: true,
						esModuleInterop: true,
						module: "esnext",
						moduleResolution: "bundler",
						resolveJsonModule: true,
						isolatedModules: true,
						jsx: "preserve",
						incremental: true,
						paths: { "@/*": ["./*"] },
						plugins: [{ name: "next" }],
					},
					include: [
						"next-env.d.ts",
						"**/*.ts",
						"**/*.tsx",
						".next/types/**/*.ts",
					],
					exclude: ["node_modules"],
				},
				null,
				2,
			),
		},

		// ── postcss.config.mjs ──────────────────────────────────────────────────
		"postcss.config.mjs": {
			content: `export default {
  plugins: {
    '@tailwindcss/postcss': {},
  },
}
`,
		},

		// ── app/globals.css ──────────────────────────────────────────────────────
		"app/globals.css": {
			content: `@import "tailwindcss";
${cssImportLines ? `\n${cssImportLines}\n` : ""}`,
		},

		// ── app/layout.tsx ───────────────────────────────────────────────────────
		"app/layout.tsx": {
			content: `import "./globals.css"
import type { ReactNode } from "react"

export const metadata = { title: "BTST Playground" }

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
`,
		},

		// ── app/page.tsx ─────────────────────────────────────────────────────────
		"app/page.tsx": {
			content: `import Link from "next/link"

export default function Home() {
  return (
    <main style={{ fontFamily: "sans-serif", padding: "2rem", maxWidth: "48rem" }}>
      <h1 style={{ fontSize: "2rem", fontWeight: "bold", marginBottom: "0.5rem" }}>
        BTST Playground
      </h1>
      <p style={{ color: "#666", marginBottom: "1.5rem" }}>
        A demo project generated by the{" "}
        <a href="https://better-stack.ai" style={{ color: "#2563eb" }}>
          BTST Playground
        </a>
        . Navigate to a plugin route below to see it in action.
      </p>
      <nav>
        <ul style={{ listStyle: "none", padding: 0, display: "flex", flexDirection: "column", gap: "0.5rem" }}>
          <li>
            <Link href="/pages/route-docs" style={{ color: "#2563eb", textDecoration: "underline" }}>
              /pages/route-docs — Browse all available routes
            </Link>
          </li>
        </ul>
      </nav>
    </main>
  )
}
`,
		},
	};

	// Merge generated files on top of the skeleton
	for (const file of generatedFiles) {
		files[file.path] = { content: file.content };
	}

	return files;
}

/**
 * Convert project files to the format expected by @stackblitz/sdk embedProject()
 */
export function toSdkFiles(projectFiles: ProjectFiles): Record<string, string> {
	return Object.fromEntries(
		Object.entries(projectFiles).map(([path, { content }]) => [path, content]),
	);
}
