export const FORM_BUILDER_COMMON = {
	// Buttons
	FORM_BUILDER_BUTTON_SAVE: "Save",
	FORM_BUILDER_BUTTON_CANCEL: "Cancel",
	FORM_BUILDER_BUTTON_DELETE: "Delete",
	FORM_BUILDER_BUTTON_CREATE: "Create",
	FORM_BUILDER_BUTTON_BACK: "Back",
	FORM_BUILDER_BUTTON_NEW_FORM: "New Form",
	FORM_BUILDER_BUTTON_SUBMIT: "Submit",

	// Labels
	FORM_BUILDER_LABEL_NAME: "Name",
	FORM_BUILDER_LABEL_SLUG: "Slug",
	FORM_BUILDER_LABEL_SLUG_DESCRIPTION: "URL-friendly identifier for this form",
	FORM_BUILDER_LABEL_DESCRIPTION: "Description",
	FORM_BUILDER_LABEL_STATUS: "Status",
	FORM_BUILDER_LABEL_CREATED_AT: "Created",
	FORM_BUILDER_LABEL_UPDATED_AT: "Last Updated",
	FORM_BUILDER_LABEL_ACTIONS: "Actions",

	// Status
	FORM_BUILDER_STATUS_LOADING: "Loading...",
	FORM_BUILDER_STATUS_SAVING: "Saving...",
	FORM_BUILDER_STATUS_DELETING: "Deleting...",
	FORM_BUILDER_STATUS_ACTIVE: "Active",
	FORM_BUILDER_STATUS_INACTIVE: "Inactive",
	FORM_BUILDER_STATUS_ARCHIVED: "Archived",

	// Errors
	FORM_BUILDER_ERROR_GENERIC: "Something went wrong",
	FORM_BUILDER_ERROR_NOT_FOUND: "Not found",
	FORM_BUILDER_ERROR_VALIDATION: "Please fix the errors above",

	// Attribution
	FORM_BUILDER_ATTRIBUTION: "Powered by BTST",
};
