export const FORM_BUILDER_SUBMISSIONS = {
	FORM_BUILDER_SUBMISSIONS_TITLE: "Submissions",
	FORM_BUILDER_SUBMISSIONS_SUBTITLE: "View form submissions",
	FORM_BUILDER_SUBMISSIONS_EMPTY: "No submissions yet",
	FORM_BUILDER_SUBMISSIONS_EMPTY_DESCRIPTION:
		"Submissions will appear here when users submit this form.",
	FORM_BUILDER_SUBMISSIONS_COLUMN_ID: "ID",
	FORM_BUILDER_SUBMISSIONS_COLUMN_DATA: "Data",
	FORM_BUILDER_SUBMISSIONS_COLUMN_SUBMITTED_AT: "Submitted",
	FORM_BUILDER_SUBMISSIONS_COLUMN_IP_ADDRESS: "IP Address",
	FORM_BUILDER_SUBMISSIONS_COLUMN_ACTIONS: "Actions",
	FORM_BUILDER_SUBMISSIONS_ACTION_VIEW: "View",
	FORM_BUILDER_SUBMISSIONS_ACTION_DELETE: "Delete",
	FORM_BUILDER_SUBMISSIONS_DELETE_CONFIRM:
		"Are you sure you want to delete this submission?",
	FORM_BUILDER_SUBMISSIONS_BACK_TO_FORM: "Back to Form",
};
